# Generated by Django 4.0.6 on 2022-08-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_event', models.CharField(max_length=100)),
                ('title_of_event', models.CharField(max_length=100)),
                ('number_of_guests', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(null=True)),
                ('hash_tag', models.CharField(max_length=50)),
                ('rsvp', models.IntegerField(blank=True, default=0)),
                ('flyer_image', models.ImageField(upload_to='invite/media')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100, verbose_name='Your full name here')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='What is your email address?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
