# Generated by Django 4.0.6 on 2022-08-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='email',
        ),
    ]
